version: "3.8"

services:
  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./src/server:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app # Bind mount the local frontend code
      - /app/node_modules # Prevent overwriting node_modules in the container
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"] # Ensure the dev server is running for live updates

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipedb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: